apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    @INCLUDE input.conf
    @INCLUDE output.conf


  input.conf: |
    [INPUT]
        Name              tail
        Path              /var/log/hello/hello.log
        Tag               hello.log
        Refresh_Interval  5
        Read_from_Head    true

  output.conf: |
    [OUTPUT]
        Name  opensearch
        Match hello.log
        Host ${FLUENT_OPENSEARCH_HOST}
        Port  ${FLUENT_OPENSEARCH_PORT}
        HTTP_User ${FLUENT_OPENSEARCH_USER}
        HTTP_Passwd ${FLUENT_OPENSEARCH_PASSWORD}
        Index hello-logs
        tls On
        tls.verify Off
        Logstash_Format Off
        Logstash_Prefix fluent-bit
        Suppress_Type_Name On
