apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  namespace: logging
spec:
  containers:
  - name: hello-container
    image: busybox
    command: ["sh", "-c"]
    args:
      - |
        while true; do
          echo "{\"timestamp\": \"$(date +%Y-%m-%dT%H:%M:%S%z)\", \"message\": \"Hello, OpenSearch Narendra!\", \"details\": {\"level\": \"info\", \"service\": \"hello-service\", \"environment\": \"production\", \"host\": \"localhost\", \"status\": \"200 OK\"}}" >> /var/log/hello/hello.log
          sleep 5
        done
    volumeMounts:
    - name: logs
      mountPath: /var/log/hello

  - name: fluent-bit
    image: fluent/fluent-bit:4.0.7
    env:
    - name: FLUENT_OPENSEARCH_HOST
      value: "opensearch-cluster-master.opensearch.svc.cluster.local"
    - name: FLUENT_OPENSEARCH_PORT
      value: "9200"
    - name: FLUENT_OPENSEARCH_USER
      value: "admin"
    - name: FLUENT_OPENSEARCH_PASSWORD
      value: "YourStrongPassword123!"
    volumeMounts:
    - name: logs
      mountPath: /var/log/hello   # same path
    - name: fluent-bit-config
      mountPath: /fluent-bit/etc/

  volumes:
  - name: logs
    emptyDir: {}
  - name: fluent-bit-config
    configMap:
      name: fluent-bit
  